### ISSUE TITLE
new-config fails with ConfigKeyError

### ISSUE THREAD

**Issue by tomato42** [sixty-north/cosmic-ray#483]
I'm running `cosmic-ray new-config cosmic-ray.toml` using 5.6.1 installed with pip3

the command fails after asking few questions:
```
$ cosmic-ray new-config cosmic-ray.toml
[?] Top-level module path: src
[?] Python version (blank for auto detection): 
[?] Test execution timeout (seconds): 50    
[?] Test command: pytest
-- MENU: Execution engine --
  (0) local
[?] Enter menu selection: 0
ConfigKeyError('operators-filter')
```

**Comment by MartinThoma** [comment]
I had the same issue with `cosmic-ray==5.6.1`.

I created the following `cosmic-ray.toml` manually:

```
[cosmic-ray]
module-path = "my_module"
python-version = ""
timeout = 10
exclude-modules = ["*/tests/*"]
test-command = "python3 -m pytest"
execution-engine.name = "local"

[cosmic-ray.cloning]
method = 'copy'
commands = ["pip install pytest",
            "pip install ."]
```

**Comment by abingham** [comment]
This is a bug in how the new operators-filter interceptor's default config was being constructed. It should be fixed soon.

**Comment by abingham** [comment]
This should be fixed in 5.6.2. If it seems to be fixed to you, please close this. Thanks!

**Comment by tomato42** [comment]
Unfortunately no, new-config still fails, but with a new error now:
```
[?] Top-level module path: src
[?] Python version (blank for auto detection): 
[?] Test execution timeout (seconds): 120
[?] Test command: pytest
-- MENU: Execution engine --
  (0) local
[?] Enter menu selection: 0
ConfigKeyError('operators-filter')
```

**Comment by abingham** [comment]
Are you sure you've got 5.6.2? Even in a brand new virtual env, I had to
run a `pip install --upgrade cosmic-ray` to get the most recent version
(i.e. to bypass my pip cache, I think).

**Comment by tomato42** [comment]
ah, yes, sorry, I did install new version system-wide, but forgot that I had a copy installed in user environment too

looks fixed, thanks!
